### ISSUE TITLE
tokio-postgres 0.6 support

### ISSUE THREAD

**Issue by shiftrtech** [Dowwie/tokio-postgres-mapper#10]
[tokio-postgres-mapper](https://github.com/Dowwie/tokio-postgres-mapper) depends on tokio-postgres = "0.5.4" i cant use it with tokio-postgres = "0.6", having this issue: 

```rust
method `from_row` has an incompatible type for trait
expected fn pointer `fn(deadpool_postgres::tokio_postgres::Row) -> std::result::Result<_, _>`
   found fn pointer `fn(tokio_postgres::Row) -> std::result::Result<_, _>`
perhaps two different versions of crate `tokio_postgres` are being used?rustc(E0053)
```

**Comment by Dowwie** [comment]
I'm short on time.  If anyone wants to work on an update, you are free to do so.  Otherwise, I'll make time for [tokio v1.0](https://github.com/tokio-rs/tokio/milestone/8), whose release is imminent.

**Comment by DominicWrege** [comment]
#11

**Comment by Dowwie** [comment]
Released (compatible with tokio v1 and tokio-postgres 0.7):
- tokio-pg-mapper 0.1.9
- tokio-pg-mapper-derive 0.1.6
