### ISSUE TITLE
Release 0.1.9 contains breaking change

### ISSUE THREAD

**Issue by dunnock** [Dowwie/tokio-postgres-mapper#12]
Hi @Dowwie , it seems 0.1.9 has breaking changes (as to updated tokio-postgres which has increased minor version). Is it possible to revert this change and release 0.2.0 with new tokio-postgres instread?

E.g. we are still on tokio-postgres 0.6 getting this error:
```
the trait bound `tokio_pg_mapper::Error: std::convert::From<tokio_postgres::Error>` is not satisfied
error[E0277]: the trait bound `tokio_pg_mapper::Error: std::convert::From<tokio_postgres::Error>` is not satisfied
  --> db/src/models/yat_json_store.rs:13:48
   |
13 | #[derive(Debug, Clone, PartialEq, PostgresMapper)]
   |                                                ^ the trait `std::convert::From<tokio_postgres::Error>` is not implemented for `tokio_pg_mapper::Error`
   |
   = help: the following implementations were found:
             <tokio_pg_mapper::Error as std::convert::From<std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>>
             <tokio_pg_mapper::Error as std::convert::From<tokio_postgres::error::Error>>
   = note: required by `std::convert::From::from`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Thank you and have a great New Year holiday!

**Comment by jmfrank63** [comment]
It took me half a day to find this bug and landed here to report it but @dunnock was faster ;-) Please consider his suggestion and remove 0.1.9 in favour of 0.2.0. Thanks

**Comment by Dowwie** [comment]
@dunnock , @jmfrank63 

Apologies for the break and wasting effort hunting down the source of the issue.  This should have been a v0.2 release.   I've consequently yanked `tokio-pg-mapper-derive  v0.1.6`  and `tokio-pg-mapper v0.1.9`  crates and replaced them with v0.2 counterparts.

https://crates.io/crates/tokio-pg-mapper
https://crates.io/crates/tokio-pg-mapper-derive
